name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y libpcre3-dev libbz2-dev zlib1g-dev libsdl2-dev libpng-dev libmpg123-dev libavcodec-dev libavformat-dev libswscale-dev libavutil-dev
    - name: checkout submodules
      run: git submodule update --init --recursive
    - name: configure
      run: ./configure
    - name: make
      run: make -j2
