name: Windows MSYS2 mingw64
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
      - name: install packages
        run: pacman --noconfirm -S --needed --overwrite git make nasm mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-zlib mingw-w64-ucrt-x86_64-libiconv mingw-w64-ucrt-x86_64-bzip2 mingw-w64-ucrt-x86_64-SDL2 mingw-w64-ucrt-x86_64-mpg123 mingw-w64-ucrt-x86_64-pcre mingw-w64-ucrt-x86_64-libpng mingw-w64-ucrt-x86_64-dav1d mingw-w64-ucrt-x86_64-libjpeg-turbo
      - name: configure
        run: ./configure
      - name: make
        run: make -j2
