name: Ubuntu latest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: true
    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y nasm libpcre3-dev libbz2-dev zlib1g-dev libsdl2-dev libpng-dev libmpg123-dev libdav1d-dev libvorbis-dev libogg-dev
    - name: configure
      run: ./configure
    - name: make
      run: make -j2
